# Generated by Django 3.2.5 on 2021-12-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField()),
                ('patient_type', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('pneumonia', models.IntegerField(default=0)),
                ('diabetes', models.IntegerField(default=0)),
                ('copd', models.IntegerField(default=0)),
                ('asthma', models.IntegerField(default=0)),
                ('inmsupr', models.IntegerField(default=0)),
                ('hypertension', models.IntegerField(default=0)),
                ('other_disease', models.IntegerField(default=0)),
                ('cardiovascular', models.IntegerField(default=0)),
                ('obesity', models.IntegerField(default=0)),
                ('renal_chronic', models.IntegerField(default=0)),
                ('tobacco', models.IntegerField(default=0)),
                ('covid_positive', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SurvivalRate',
            fields=[
                ('rate', models.FloatField()),
                ('health_profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.healthprofile')),
            ],
        ),
    ]
