# Generated by Django 4.0 on 2021-12-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivalrate',
            old_name='rate',
            new_name='died',
        ),
    ]
