# Generated by Django 4.0 on 2021-12-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rate_survivalrate_died'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurvivalRate',
            new_name='SurvivalPrediction',
        ),
    ]
