# Generated by Django 4.0 on 2021-12-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_survivalrate_survivalprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.IntegerField()),
                ('entry_date', models.TextField(max_length=25)),
                ('date_symptoms', models.TextField(max_length=25)),
                ('date_died', models.TextField(max_length=25)),
                ('intubed', models.IntegerField()),
                ('pneumonia', models.IntegerField()),
                ('age', models.IntegerField()),
                ('pregnancy', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('copd', models.IntegerField()),
                ('asthma', models.IntegerField()),
                ('inmsupr', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('other_disease', models.IntegerField()),
                ('cardiovascular', models.IntegerField()),
                ('obesity', models.IntegerField()),
                ('renal_chronic', models.IntegerField()),
                ('tobacco', models.IntegerField()),
                ('contact_other_covid', models.IntegerField()),
                ('covid_res', models.IntegerField()),
                ('icu', models.IntegerField()),
            ],
        ),
    ]
