# Generated by Django 4.0 on 2021-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coviddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddata',
            name='patient_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
