# Generated by Django 4.0 on 2021-12-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_coviddata_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddata',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
