# Generated by Django 4.0 on 2021-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coviddata_patient_id_alter_coviddata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComorbidityCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pneumonia', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('copd', models.IntegerField()),
                ('asthma', models.IntegerField()),
                ('inmsupr', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('other_disease', models.IntegerField()),
                ('cardiovascular', models.IntegerField()),
                ('obesity', models.IntegerField()),
                ('renal_chronic', models.IntegerField()),
                ('tobacco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CovidDeathAgeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurvivalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='CovidData',
        ),
    ]
